/**
 * Profile taxonomy — single source of truth for profile detail options.
 * See docs/PROFILE_TAXONOMY.md.
 */

export type TaxonomyOption = { value: string; labelKey: string };

export const TAXONOMY = {
  careerStageOptions: [
    { value: "early_career", labelKey: "taxonomy.careerStage.early_career" },
    { value: "emerging", labelKey: "taxonomy.careerStage.emerging" },
    { value: "mid_career", labelKey: "taxonomy.careerStage.mid_career" },
    { value: "established", labelKey: "taxonomy.careerStage.established" },
    { value: "institution", labelKey: "taxonomy.careerStage.institution" },
    { value: "private_practice", labelKey: "taxonomy.careerStage.private_practice" },
    { value: "prefer_not", labelKey: "taxonomy.careerStage.prefer_not" },
  ] as TaxonomyOption[],

  ageBandOptions: [
    { value: "u18", labelKey: "taxonomy.ageBand.u18" },
    { value: "18_24", labelKey: "taxonomy.ageBand.18_24" },
    { value: "25_34", labelKey: "taxonomy.ageBand.25_34" },
    { value: "35_44", labelKey: "taxonomy.ageBand.35_44" },
    { value: "45_54", labelKey: "taxonomy.ageBand.45_54" },
    { value: "55_64", labelKey: "taxonomy.ageBand.55_64" },
    { value: "65p", labelKey: "taxonomy.ageBand.65p" },
    { value: "prefer_not", labelKey: "taxonomy.ageBand.prefer_not" },
  ] as TaxonomyOption[],

  themeOptions: [
    { value: "identity_body", labelKey: "taxonomy.theme.identity_body" },
    { value: "memory_archive", labelKey: "taxonomy.theme.memory_archive" },
    { value: "nature_ecology", labelKey: "taxonomy.theme.nature_ecology" },
    { value: "tech_future", labelKey: "taxonomy.theme.tech_future" },
    { value: "urban_city", labelKey: "taxonomy.theme.urban_city" },
    { value: "spirituality_myth", labelKey: "taxonomy.theme.spirituality_myth" },
    { value: "politics_society", labelKey: "taxonomy.theme.politics_society" },
    { value: "migration_diaspora", labelKey: "taxonomy.theme.migration_diaspora" },
    { value: "labor_industry", labelKey: "taxonomy.theme.labor_industry" },
    { value: "time_impermanence", labelKey: "taxonomy.theme.time_impermanence" },
    { value: "love_intimacy", labelKey: "taxonomy.theme.love_intimacy" },
    { value: "violence_conflict", labelKey: "taxonomy.theme.violence_conflict" },
    { value: "humor_play", labelKey: "taxonomy.theme.humor_play" },
    { value: "dreams_surreal", labelKey: "taxonomy.theme.dreams_surreal" },
    { value: "minimal_silence", labelKey: "taxonomy.theme.minimal_silence" },
    { value: "material_process", labelKey: "taxonomy.theme.material_process" },
    { value: "portrait_figure", labelKey: "taxonomy.theme.portrait_figure" },
    { value: "landscape", labelKey: "taxonomy.theme.landscape" },
    { value: "abstraction", labelKey: "taxonomy.theme.abstraction" },
    { value: "conceptual_text", labelKey: "taxonomy.theme.conceptual_text" },
    { value: "pattern_ornament", labelKey: "taxonomy.theme.pattern_ornament" },
    { value: "light_space", labelKey: "taxonomy.theme.light_space" },
    { value: "sound_performance", labelKey: "taxonomy.theme.sound_performance" },
    { value: "architecture", labelKey: "taxonomy.theme.architecture" },
    { value: "science_cosmos", labelKey: "taxonomy.theme.science_cosmos" },
    { value: "ritual_tradition", labelKey: "taxonomy.theme.ritual_tradition" },
    { value: "consumer_media", labelKey: "taxonomy.theme.consumer_media" },
    { value: "healing_care", labelKey: "taxonomy.theme.healing_care" },
    { value: "other", labelKey: "taxonomy.theme.other" },
  ] as TaxonomyOption[],

  mediumOptions: [
    { value: "painting", labelKey: "taxonomy.medium.painting" },
    { value: "drawing", labelKey: "taxonomy.medium.drawing" },
    { value: "sculpture", labelKey: "taxonomy.medium.sculpture" },
    { value: "photography", labelKey: "taxonomy.medium.photography" },
    { value: "print_edition", labelKey: "taxonomy.medium.print_edition" },
    { value: "textile_fiber", labelKey: "taxonomy.medium.textile_fiber" },
    { value: "ceramics", labelKey: "taxonomy.medium.ceramics" },
    { value: "wood_metal", labelKey: "taxonomy.medium.wood_metal" },
    { value: "collage_mixed", labelKey: "taxonomy.medium.collage_mixed" },
    { value: "installation", labelKey: "taxonomy.medium.installation" },
    { value: "video", labelKey: "taxonomy.medium.video" },
    { value: "new_media", labelKey: "taxonomy.medium.new_media" },
    { value: "performance", labelKey: "taxonomy.medium.performance" },
    { value: "other", labelKey: "taxonomy.medium.other" },
  ] as TaxonomyOption[],

  styleOptions: [
    { value: "minimalism", labelKey: "taxonomy.style.minimalism" },
    { value: "maximalism", labelKey: "taxonomy.style.maximalism" },
    { value: "geometric", labelKey: "taxonomy.style.geometric" },
    { value: "gestural", labelKey: "taxonomy.style.gestural" },
    { value: "lyrical", labelKey: "taxonomy.style.lyrical" },
    { value: "monochrome", labelKey: "taxonomy.style.monochrome" },
    { value: "figurative", labelKey: "taxonomy.style.figurative" },
    { value: "narrative", labelKey: "taxonomy.style.narrative" },
    { value: "surreal", labelKey: "taxonomy.style.surreal" },
    { value: "pop", labelKey: "taxonomy.style.pop" },
    { value: "expressionism", labelKey: "taxonomy.style.expressionism" },
    { value: "conceptual", labelKey: "taxonomy.style.conceptual" },
    { value: "text_based", labelKey: "taxonomy.style.text_based" },
    { value: "photoreal", labelKey: "taxonomy.style.photoreal" },
    { value: "documentary", labelKey: "taxonomy.style.documentary" },
    { value: "site_specific", labelKey: "taxonomy.style.site_specific" },
    { value: "experimental", labelKey: "taxonomy.style.experimental" },
    { value: "craft_forward", labelKey: "taxonomy.style.craft_forward" },
    { value: "digital", labelKey: "taxonomy.style.digital" },
    { value: "other", labelKey: "taxonomy.style.other" },
  ] as TaxonomyOption[],

  priceBandOptions: [
    { value: "u500", labelKey: "taxonomy.priceBand.u500" },
    { value: "500_1k", labelKey: "taxonomy.priceBand.500_1k" },
    { value: "1k_2_5k", labelKey: "taxonomy.priceBand.1k_2_5k" },
    { value: "2_5k_5k", labelKey: "taxonomy.priceBand.2_5k_5k" },
    { value: "5k_10k", labelKey: "taxonomy.priceBand.5k_10k" },
    { value: "10k_25k", labelKey: "taxonomy.priceBand.10k_25k" },
    { value: "25k_50k", labelKey: "taxonomy.priceBand.25k_50k" },
    { value: "50k_100k", labelKey: "taxonomy.priceBand.50k_100k" },
    { value: "100k_p", labelKey: "taxonomy.priceBand.100k_p" },
    { value: "not_sure", labelKey: "taxonomy.priceBand.not_sure" },
    { value: "prefer_not", labelKey: "taxonomy.priceBand.prefer_not" },
  ] as TaxonomyOption[],

  acquisitionChannelOptions: [
    { value: "gallery", labelKey: "taxonomy.acquisitionChannel.gallery" },
    { value: "art_fair", labelKey: "taxonomy.acquisitionChannel.art_fair" },
    { value: "auction", labelKey: "taxonomy.acquisitionChannel.auction" },
    { value: "online", labelKey: "taxonomy.acquisitionChannel.online" },
    { value: "commission", labelKey: "taxonomy.acquisitionChannel.commission" },
    { value: "advisor", labelKey: "taxonomy.acquisitionChannel.advisor" },
    { value: "other", labelKey: "taxonomy.acquisitionChannel.other" },
  ] as TaxonomyOption[],

  affiliationOptions: [
    { value: "independent", labelKey: "taxonomy.affiliation.independent" },
    { value: "gallery", labelKey: "taxonomy.affiliation.gallery" },
    { value: "museum", labelKey: "taxonomy.affiliation.museum" },
    { value: "nonprofit", labelKey: "taxonomy.affiliation.nonprofit" },
    { value: "academic", labelKey: "taxonomy.affiliation.academic" },
    { value: "other", labelKey: "taxonomy.affiliation.other" },
  ] as TaxonomyOption[],

  educationTypeOptions: [
    { value: "hs_art", labelKey: "taxonomy.educationType.hs_art" },
    { value: "ba", labelKey: "taxonomy.educationType.ba" },
    { value: "bfa", labelKey: "taxonomy.educationType.bfa" },
    { value: "ma", labelKey: "taxonomy.educationType.ma" },
    { value: "mfa", labelKey: "taxonomy.educationType.mfa" },
    { value: "phd", labelKey: "taxonomy.educationType.phd" },
    { value: "other", labelKey: "taxonomy.educationType.other" },
  ] as TaxonomyOption[],

  regionOptions: [
    { value: "us_west", labelKey: "taxonomy.region.us_west" },
    { value: "us_east", labelKey: "taxonomy.region.us_east" },
    { value: "us_midwest", labelKey: "taxonomy.region.us_midwest" },
    { value: "us_south", labelKey: "taxonomy.region.us_south" },
    { value: "kr_seoul", labelKey: "taxonomy.region.kr_seoul" },
    { value: "kr_metro", labelKey: "taxonomy.region.kr_metro" },
    { value: "kr_other", labelKey: "taxonomy.region.kr_other" },
    { value: "eu_west", labelKey: "taxonomy.region.eu_west" },
    { value: "eu_central", labelKey: "taxonomy.region.eu_central" },
    { value: "eu_east", labelKey: "taxonomy.region.eu_east" },
    { value: "jp", labelKey: "taxonomy.region.jp" },
    { value: "cn", labelKey: "taxonomy.region.cn" },
    { value: "sea", labelKey: "taxonomy.region.sea" },
    { value: "oceania", labelKey: "taxonomy.region.oceania" },
    { value: "latam", labelKey: "taxonomy.region.latam" },
    { value: "mena", labelKey: "taxonomy.region.mena" },
    { value: "africa", labelKey: "taxonomy.region.africa" },
    { value: "other", labelKey: "taxonomy.region.other" },
  ] as TaxonomyOption[],
} as const;

/** Max counts for multi-select (from PROFILE_TAXONOMY) */
export const TAXONOMY_LIMITS = {
  themes: 5,
  themesOther: 2,
  keywords: 10,
  mediums: 4,
  mediumsOther: 2,
  styles: 6,
  stylesOther: 2,
  acquisitionChannels: 4,
  acquisitionChannelsOther: 2,
  programFocus: 5,
  priceBand: 5,
} as const;
