/**
 * Sprint 4 P0-A — Privacy guard: telemetry payloads must never carry
 * bearer-secret-shaped keys.
 *
 * Statically scans `src/**` for telemetry call sites and asserts that
 * the inline object literal arguments do not contain forbidden keys
 * such as `token`, `password`, `secret`, `apiKey`, `authorization`,
 * `cookie`, `magicLink`, or `inviteToken`. The intent is *not* to
 * stop normal `token` *URL parameters* from existing — it is to stop
 * those values from being persisted in beta analytics rows.
 *
 * Limitations (deliberate, documented):
 *   - Only inspects inline object literals at the call site. Helpers
 *     that build payloads elsewhere are not statically traceable here;
 *     `lib/supabase/priceInquiries.ts#sanitizeInquirySource` is the
 *     runtime guard for those (covered by `tests/inquiry-source.test.ts`).
 *   - Spread (`...payload`) is allowed: we cannot statically read the
 *     spread object, so the test trusts the spread source — `seq` /
 *     `surface` / `session_id` from `feedEventBase()` etc. The spread
 *     sources themselves never carry forbidden keys (audited at write
 *     time of this test).
 *   - Identifier-only entries (e.g. `{ shortlist_id }`) are read by
 *     their property name, so a developer cannot smuggle a forbidden
 *     payload by aliasing.
 *
 * If this test ever fails, do NOT widen the regex. Fix the call site
 * to drop the secret-shaped key first.
 */

import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(__dirname, "..", "src");

const TELEMETRY_FUNCS = [
  "logBetaEventSync",
  "logBetaEvent",
  "logFeedEvent",
];

// Case-insensitive — covers `Token`, `TOKEN`, etc. The regex deliberately
// matches as a *substring* of the property name so `share_token`,
// `inviteToken`, `magicLink`, `apiKey`, etc. all trip the guard.
const FORBIDDEN_KEY_RE =
  /(token|password|secret|apikey|authorization|cookie|magic|bearer|sessionsecret)/i;

// `feed_session_id` is a synthetic telemetry id (uuid-ish) generated by
// `lib/feed/telemetry.ts#getFeedSessionId`, NOT a Supabase auth session
// secret. Allow it explicitly so the broader `secret`/`session*` regex
// doesn't false-positive.
const ALLOWLIST = new Set<string>([
  "feed_session_id",
  "source_feed_session_id",
]);

type Finding = { file: string; line: number; key: string; snippet: string };

async function walk(dir: string, out: string[] = []): Promise<string[]> {
  const ents = await fs.readdir(dir, { withFileTypes: true });
  for (const e of ents) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name === "node_modules" || e.name === ".next") continue;
      await walk(full, out);
    } else if (/\.(ts|tsx)$/.test(e.name)) {
      out.push(full);
    }
  }
  return out;
}

/**
 * Returns the index of the matching closing bracket for the bracket at
 * `start`, or -1 if no match. Tracks (), {}, [], and skips strings /
 * template literals / comments. Cheap brace-balanced scanner — good
 * enough for our well-formed source inputs.
 */
function matchClose(src: string, start: number): number {
  const open = src[start];
  const close = open === "(" ? ")" : open === "{" ? "}" : open === "[" ? "]" : "";
  if (!close) return -1;
  let depth = 0;
  let i = start;
  while (i < src.length) {
    const c = src[i];
    // Block comment.
    if (c === "/" && src[i + 1] === "*") {
      const end = src.indexOf("*/", i + 2);
      if (end === -1) return -1;
      i = end + 2;
      continue;
    }
    // Line comment.
    if (c === "/" && src[i + 1] === "/") {
      const nl = src.indexOf("\n", i + 2);
      i = nl === -1 ? src.length : nl + 1;
      continue;
    }
    // Strings (single, double).
    if (c === '"' || c === "'") {
      const quote = c;
      i += 1;
      while (i < src.length) {
        if (src[i] === "\\") { i += 2; continue; }
        if (src[i] === quote) { i += 1; break; }
        i += 1;
      }
      continue;
    }
    // Template literal — skip with shallow ${} support.
    if (c === "`") {
      i += 1;
      while (i < src.length) {
        if (src[i] === "\\") { i += 2; continue; }
        if (src[i] === "`") { i += 1; break; }
        if (src[i] === "$" && src[i + 1] === "{") {
          const inner = matchClose(src, i + 1);
          if (inner === -1) return -1;
          i = inner + 1;
          continue;
        }
        i += 1;
      }
      continue;
    }
    if (c === "(" || c === "{" || c === "[") depth += 1;
    else if (c === ")" || c === "}" || c === "]") {
      depth -= 1;
      if (depth === 0 && c === close) return i;
    }
    i += 1;
  }
  return -1;
}

/**
 * Walk an object-literal body and yield every key. Handles:
 *   - shorthand `{ token }` → key = "token"
 *   - explicit `{ token: x }` → key = "token"
 *   - quoted `{ "token": x }` → key = "token"
 *   - nested objects → recurses
 * Skips spread (`...something`) deliberately — see test header.
 */
function* iterKeys(body: string): Generator<string> {
  let i = 0;
  while (i < body.length) {
    // Skip whitespace, commas, newlines.
    while (i < body.length && /[\s,]/.test(body[i])) i += 1;
    if (i >= body.length) break;

    // Skip line comments — otherwise an English comment like "(NOT the
    // room token)" would have its words treated as object keys.
    if (body[i] === "/" && body[i + 1] === "/") {
      const nl = body.indexOf("\n", i + 2);
      i = nl === -1 ? body.length : nl + 1;
      continue;
    }
    // Skip block comments.
    if (body[i] === "/" && body[i + 1] === "*") {
      const end = body.indexOf("*/", i + 2);
      i = end === -1 ? body.length : end + 2;
      continue;
    }

    // Skip spread (... ).
    if (body[i] === "." && body[i + 1] === "." && body[i + 2] === ".") {
      // advance to next top-level comma at depth 0
      let depth = 0;
      while (i < body.length) {
        const c = body[i];
        if (c === "(" || c === "{" || c === "[") depth += 1;
        else if (c === ")" || c === "}" || c === "]") depth -= 1;
        else if (c === "," && depth === 0) break;
        i += 1;
      }
      continue;
    }

    // Quoted key.
    if (body[i] === '"' || body[i] === "'") {
      const quote = body[i];
      const end = body.indexOf(quote, i + 1);
      if (end === -1) return;
      const key = body.slice(i + 1, end);
      yield key;
      i = end + 1;
      // skip until ":" then to end of value
      const colon = body.indexOf(":", i);
      if (colon === -1) return;
      i = colon + 1;
      i = skipValue(body, i);
      continue;
    }

    // Bare identifier (shorthand or `key: value`).
    const m = /^[A-Za-z_$][A-Za-z0-9_$]*/.exec(body.slice(i));
    if (!m) {
      i += 1;
      continue;
    }
    const key = m[0];
    yield key;
    i += key.length;
    // Skip whitespace then check if next is `:` (explicit value) or
    // shorthand (`,` / `}` / end).
    while (i < body.length && /\s/.test(body[i])) i += 1;
    if (body[i] === ":") {
      i += 1;
      // Recurse into nested objects.
      while (i < body.length && /\s/.test(body[i])) i += 1;
      if (body[i] === "{") {
        const close = matchClose(body, i);
        if (close === -1) return;
        const inner = body.slice(i + 1, close);
        for (const k of iterKeys(inner)) yield k;
        i = close + 1;
      } else {
        i = skipValue(body, i);
      }
    }
    // shorthand → loop continues to next entry
  }
}

function skipValue(src: string, i: number): number {
  let depth = 0;
  while (i < src.length) {
    const c = src[i];
    if (c === '"' || c === "'") {
      const quote = c;
      i += 1;
      while (i < src.length) {
        if (src[i] === "\\") { i += 2; continue; }
        if (src[i] === quote) { i += 1; break; }
        i += 1;
      }
      continue;
    }
    if (c === "`") {
      i += 1;
      while (i < src.length) {
        if (src[i] === "\\") { i += 2; continue; }
        if (src[i] === "`") { i += 1; break; }
        i += 1;
      }
      continue;
    }
    if (c === "(" || c === "{" || c === "[") { depth += 1; i += 1; continue; }
    if (c === ")" || c === "}" || c === "]") {
      if (depth === 0) return i;
      depth -= 1;
      i += 1;
      continue;
    }
    if (c === "," && depth === 0) return i;
    i += 1;
  }
  return i;
}

(async () => {
  const files = await walk(ROOT);
  const findings: Finding[] = [];
  let callSitesScanned = 0;

  for (const file of files) {
    const src = await fs.readFile(file, "utf-8");
    for (const fn of TELEMETRY_FUNCS) {
      const re = new RegExp(`\\b${fn}\\s*\\(`, "g");
      let m: RegExpExecArray | null;
      while ((m = re.exec(src)) !== null) {
        const openParen = m.index + m[0].length - 1;
        const closeParen = matchClose(src, openParen);
        if (closeParen === -1) continue;
        callSitesScanned += 1;
        const args = src.slice(openParen + 1, closeParen);
        // Find the FIRST top-level "{" — that's the payload object.
        let depth = 0;
        let payloadStart = -1;
        for (let k = 0; k < args.length; k++) {
          const c = args[k];
          if (c === "(" || c === "[") depth += 1;
          else if (c === ")" || c === "]") depth -= 1;
          else if (c === "{" && depth === 0) {
            payloadStart = k;
            break;
          }
        }
        if (payloadStart === -1) continue;
        const payloadClose = matchClose(args, payloadStart);
        if (payloadClose === -1) continue;
        const body = args.slice(payloadStart + 1, payloadClose);

        for (const key of iterKeys(body)) {
          if (ALLOWLIST.has(key)) continue;
          if (FORBIDDEN_KEY_RE.test(key)) {
            const lineNo = src.slice(0, m.index).split("\n").length;
            findings.push({
              file: path.relative(path.resolve(__dirname, ".."), file),
              line: lineNo,
              key,
              snippet: src.slice(m.index, Math.min(src.length, m.index + 120)).replace(/\s+/g, " "),
            });
          }
        }
      }
    }
  }

  if (findings.length > 0) {
    console.error("\n[privacy-token-audit] forbidden keys found in telemetry payloads:");
    for (const f of findings) {
      console.error(`  ${f.file}:${f.line}  key="${f.key}"`);
      console.error(`    near: ${f.snippet}`);
    }
    console.error(`\nForbidden keys: ${FORBIDDEN_KEY_RE.source}`);
    console.error(`Allowlist: ${[...ALLOWLIST].join(", ")}`);
    process.exit(1);
  }

  assert.ok(callSitesScanned > 0, "scanner must find at least one telemetry call site");
  console.log(
    `privacy-token-audit.test.ts: ok (scanned ${callSitesScanned} telemetry call sites across ${files.length} files)`,
  );
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
